spring:
  application:
    name: Zin Application
  flyway:
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studyjpa
    username: ${db.username:root}
    password: ${db.password:1234}
  jpa:
    hibernate:
      ddl-auto: ${ddl.auto:update}
